### ISSUE TITLE
pdfium CMakeOutput error

### ISSUE THREAD

**Issue by Sathish0225** [bblanchon/pdfium-binaries#111]
I'm getting below error message while build flutter windows application using printing and pdfium package.

```powershell
[  +16 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-mkdir.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-download.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-update.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-patch.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-configure.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-build.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-install.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ed5e2c6df99befe2067df5ae37c2568c\pdfium-download-test.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\cfa2eb2c89fd8a228039b18d43b0d66b\pdfium-download-complete.rule;D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\CMakeFiles\ee3bb7a17a44bba64dcf1ce238bf059a\pdfium-download.rule' exited with code 9009. [D:\Development\Mobile
App\tripper_vms_desktop\build\windows\pdfium-download\pdfium-download.vcxproj]
[  +25 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
[   +4 ms]   Build step for pdfium failed: 1
[        ] Call Stack (most recent call first):
[        ]   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "D:/Development/Mobile App/tripper_vms_desktop/build/windows/CMakeFiles/CMakeOutput.log".
[  +25 ms] Building Windows application... (completed in 8.2s)
[   +2 ms] "flutter windows" took 13,754ms.
[   +5 ms] Unable to generate build files
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmakeGeneration (package:flutter_tools/src/windows/build_windows.dart:176:5)
           <asynchronous suspension>
           #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:85:5)
           <asynchronous suspension>
           #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
``` 
can any one suggest me what to do on this issue ?

**Comment by Sathish0225** [comment]
i found the issue and fixed it.
this error message is due to Visual Studio Build Tool 16 2019
after upgrading it to Visual Studio Build Tool 17 2022, error message disappeared

**Comment by bblanchon** [comment]
Thanks for the update, @Sathish0225; I'm sure this will help others.
