### ISSUE TITLE
Shared libraries cannot locate symbol "__register_atfork", Android API 21-22-23

### ISSUE THREAD

**Issue by lion0508** [bblanchon/pdfium-binaries#147]
Hello,
When im trying to use .so on Android 5.1, i received this error:
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/io.legere.pdfiumandroidkt-1/lib/arm64/libpdfium_v2.so"

**Comment by lion0508** [comment]
Similar issue i have, when im trying to use .so on Android 6, i received this error:
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__write_chk" referenced by "/data/app/io.legere.pdfiumandroidkt-1/lib/arm64/libpdfium_v2.so"

**Comment by lion0508** [comment]
Hello
Thanks, for your response, as i understand correctly, for quick fix, i should use this way for that:
<img width="572" alt="chrome_2023-12-01_23-14-06" src="https://github.com/bblanchon/pdfium-binaries/assets/12742655/9950377c-ab12-45d1-9754-e6621df329e7">

Is it correct understanding from my side?

**Comment by lion0508** [comment]
I have one more small question, how i can include another *.so libs together with libpdfium.so:
<img width="139" alt="chrome_2023-12-01_23-20-47" src="https://github.com/bblanchon/pdfium-binaries/assets/12742655/309adb0a-d56e-4092-8f25-27c42718e219">

**Comment by bblanchon** [comment]
You can try to lower the requirements, but I'm pretty sure the PDFium and Chromium teams already configured it to support the oldest possible Android version.
If you need to support an old version of Android, you'll probably have to use an old version of PDFium.

The `libpdfium.so` provided here should already be bundled with all the required dependencies.

**Comment by bblanchon** [comment]
Chromium dropped support for Android API 23 a year ago:
https://groups.google.com/a/chromium.org/g/chromium-dev/c/z_RvoPoIeoM

**Comment by lion0508** [comment]
@bblanchon I added some changes for patches:
1. Added changes for "shared_library" patches/android/build.patch
<img width="437" alt="2023-12-03_19-10-20" src="https://github.com/bblanchon/pdfium-binaries/assets/12742655/f4ca55dd-c923-42e3-ba0b-f19e8d4e11c2">
2. Created new patch and added changes regarding "default_min_sdk_version"
<img width="467" alt="2023-12-03_19-12-07" src="https://github.com/bblanchon/pdfium-binaries/assets/12742655/e548e2f9-1600-4659-8bf3-551436021ad9">


Now it works for Android 23!
For Android 21-22 i received error ""

Do you have any ideas, regarding Android 21-22? Or i should use older version of pdfium which is supported minimum Android 21-22, what do you think?

**Comment by bblanchon** [comment]
You should address these questions to the official PDFium mailing list.

**Comment by lion1988dev** [comment]
Hello, @bblanchon Could you provide please link, of your latest version of so libs, which supported Android 23 API?

**Comment by bblanchon** [comment]
According to [the conversation mentioned above](https://groups.google.com/a/chromium.org/g/chromium-dev/c/z_RvoPoIeoM), the commit that dropped the support for Android API level 23 is this one:
https://chromium-review.googlesource.com/c/chromium/src/+/4000311

It was rolled out to PDFium with this commit:
https://pdfium.googlesource.com/pdfium/+/e57c44ecfebda5bab1fd1d6aebbfdd3e56f5b97f

The first build that included this change is [110.0.5459.0](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F5459).
The last build before this change is [110.0.5445.0](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F5445)

**Comment by lion1988dev** [comment]
Thanks for your response and links! Last question, could you provide please link, of your latest version of so libs:
- Which supported Android 21 API?

**Comment by lion1988dev** [comment]
I have tried this build so libs [8.0.4736.0](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4736), but i received this error:

No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
2024-03-12 16:24:04.364  2587-2587  PDFView                 com.github.barteksc.sample           E  load pdf error
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
                                                                                                    	at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
                                                                                                    	at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:132)
                                                                                                    	at com.github.barteksc.pdfviewer.source.AssetSource.createDocument(AssetSource.java:41)
                                                                                                    	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
                                                                                                    	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:27)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                    	at java.lang.Thread.run(Thread.java:818)

Could you check please, what can be wrong?

**Comment by lion1988dev** [comment]
@varahash Thanks for your investigation, let me check this solution, I will try to create patch with these changes and will rebuild so files. Will let you know after checking
