### ISSUE TITLE
RuntimeError: No pre-built binaries available for <Host: linux s390x, glibc 2.35>

### ISSUE THREAD

**Issue by sandeepb2013** [bblanchon/pdfium-binaries#166]
Hi,

i'm trying to install python-docTR on S390x, but dependency pypdfium2 build failed.
i'm tring to install pypdfium2 from pip getting the following error .

`pip install pypdfium2
Collecting pypdfium2
  Downloading pypdfium2-4.30.0.tar.gz (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.2/140.2 kB 3.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-iw42b6xf/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-iw42b6xf/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-iw42b6xf/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 161, in <module>
        File "<string>", line 152, in main
        File "/tmp/pip-install-96eku2nd/pypdfium2_5345d99864474a78ac39d1b0c222be99/setupsrc/pypdfium2_setup/packaging_base.py", line 610, in parse_pl_spec
          raise RuntimeError(f"No pre-built binaries available for {Host}. You may place custom binaries & bindings in data/sourcebuild and install with `{PlatSpec_EnvVar}=sourcebuild`.")
      RuntimeError: No pre-built binaries available for <Host: linux s390x, glibc 2.35>. You may place custom binaries & bindings in data/sourcebuild and install with `PDFIUM_PLATFORM=sourcebuild`.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by sandeepb2013** [comment]
@bblanchon 
raised concern regarding the same with PDFium community.
[https://github.com/pypdfium2-team/pypdfium2/issues/313]

let me know if i can do anything from my end to move forward.
Thanks.

**Comment by mara004** [comment]
@sandeepb2013 Sorry for the late reply, I missed this thread.

> raised concern regarding the same with PDFium community.
> [https://github.com/pypdfium2-team/pypdfium2/issues/313]

I think you may have confused pypdfium2 and pdfium here. You can reach out to pdfium at its mailing list: https://groups.google.com/g/pdfium
or maybe the bug tracker: https://issues.chromium.org/issues?q=componentid:1586257%2B

-----

In the meantime, you could consider the libreoffice trick: https://github.com/pypdfium2-team/pypdfium2/issues/313#issuecomment-2093029127

**Comment by sandeepb2013** [comment]
@mara004 sorry for the late response, thanks for your reference i'll be looking into the pdfium team. i''l keep you posted the updates.

**Comment by Aakash2512git** [comment]
@mara004  Any findings regarding this issue?

**Comment by mara004** [comment]
> @mara004 Any findings regarding this issue?

I'm not aware of any activity on this, and searching pdfium's bug tracker for "s390x" did not yield any entries.

mgiessing recently created a patch for ppc64le (see https://github.com/bblanchon/pdfium-binaries/issues/187, https://groups.google.com/g/pdfium/c/z1jKcpqtXpc/), so I suppose it might be possible to do something similar for s390x. However, this would need to be done by someone who has access to the platform (we don't).

Alternatively, you could file an issue with pdfium. I doubt they have access to s390x, but maybe they can provide some tips.

Side-note: pdfium's built system is great for cross-compilation to supported targets, but awful for native compilation, especially on uncommon platforms. An alternative build system designed to play well with native compilation, and using system tools/libs rather than relying on a big external toolchain would be appreciated, but this is out of my hands. There used to be a [pdfium-cmake project](https://github.com/madebr/pdfium-cmake), which still builds, but unfortunately the resulting binaries are incomplete.

**Comment by Aakash2512git** [comment]
ok thank you for response

**Comment by mara004** [comment]
It looks like this is not just hardcoding new platform handlers as in #187, but finally a more portable approach.
The shortcomings of pdfium's default non-portable, bloated build have been vexing ever since I started working on pypdfium2, so this might be a light at the end of the tunnel.
Also, it sounds like Fedora might be the first distribution taking steps towards packaging pdfium as an independent shared library.

**Comment by tiran** [comment]
Actually Arch had PDFium far longer. The Arch Linux `libpdfium-nojs` package was created in 2017, https://aur.archlinux.org/packages/libpdfium-nojs . My https://github.com/tiran/libpdfium/ repo is an attempt to upstream my internal work for Red Hat's RHELAI product and [IBM Deep Search](https://github.com/DS4SD/)'s Docling.

**Comment by tiran** [comment]
PS: PDFium does not work correctly on s390x. I have found a handful of endianess bugs already. There are probably more. I would not use PDFium on s390x until it has been thoroughly vetted for big endian platforms.

**Comment by mara004** [comment]
Thanks for the pointers. I wasn't aware of the `libpdfium-nojs` AUR yet.
As for s390x (or other special architectures), at least we're able to build, but I agree finding and fixing bugs is the next step.
The pdfium Readme actually acknowledges the endianess problems:
> It is expected that there are still some places lurking in the code which will not function properly on big-endian architectures. Bugs and/or patches are welcome, however providing this support is not a priority at this time.

**Comment by mara004** [comment]
> Edit: Oh, no, turns out pypdfium2's test suite isn't actually run yet, because there are no pillow/numpy prebuilds on PyPI for s390x. I need to set something up with the container distro's python.

I'm about to set up post-cibuildwheel docker testing to excercise pypdfium2's test suite on all targets, see
https://github.com/pypdfium2-team/pypdfium2/pull/404/changes

Indeed, on s390x, 13 test cases fail, of which 8 exercise opening encrypted pdfs, which seems to be broken on big endian.
The other 5 failures are pixel / image compare tests.

We also get 3 (different) pixel test failures on musllinux armv7l.

**Comment by mara004** [comment]
Just saw in https://chromium.googlesource.com/chromium/src/build.git/+diff/613f5c13bccb..73c0fa98c5cf/ that upstream have added an s390x sysroot.

Maybe it is now possible to cross-compile s390x with Chromium toolchain?
I'm guessing it would still lack the libclang-rt builtins, but they could probably just be skipped like we do with MIPS. (Should be possible to cross-compile them somehow, but I never really figured out how to do it...)

**Comment by bblanchon** [comment]
[install-sysroot.py](https://chromium.googlesource.com/chromium/src/build.git/+/refs/heads/main/linux/sysroot_scripts/install-sysroot.py) doesn't support s390x yet.

**Comment by mara004** [comment]
True. I'll try to patch it in though, there's a chance we can just add it to those platform listings at the top.
The difficult bit, I think, is building the sysroot. Installing a prebuilt sysroot should be feasible.
